### ISSUE TITLE
configure失败，另外附strace最后一段的载图

### ISSUE THREAD

**Issue by chengok888** [SkyAPM/SkyAPM-php-sdk#451]
![image](https://user-images.githubusercontent.com/35942250/143399482-2b49b7f9-4ccf-43ed-98bf-442a8a009f61.png)
![image](https://user-images.githubusercontent.com/35942250/143399897-b4f65f1e-85a7-475a-817f-44e07337c8db.png)

**Comment by chengok888** [comment]
![image](https://user-images.githubusercontent.com/35942250/143400238-345cd030-ba2f-48c0-b248-50d77c798da6.png)
php的版本为7.4.11

**Comment by Anoxia** [comment]
很显然呀，貌似skywalking扩展只支持NTS模式

**Comment by chengok888** [comment]
> 很显然呀，貌似skywalking扩展只支持NTS模式
大佬  请问应该如何安装php插件呢?

**Comment by chengok888** [comment]
![image](https://user-images.githubusercontent.com/35942250/143832975-4d12a82c-30fb-43e3-9d69-028d7fe183cf.png)
我原先以为是php的版本问题   所以把php换成了7.2.33的版本，系统为centos7.7 ，教程是用下面这个说明文档中的教程，但还是会发生上面这个错误，奇怪的是这个文件'libgrpc.a' 我全盘搜索，也没有找到啊
https://github.com/SkyAPM/SkyAPM-php-sdk/blob/master/docs/BUILDING.md

**Comment by heyanlong** [comment]
Need to provide a complete compilation command and output

**Comment by chengok888** [comment]
终于安装成功了，主要是PHP版本的问题...我把php的版本降成7.3.33就能安装成功，但又出现另一个问题:
https://github.com/SkyAPM/SkyAPM-php-sdk/issues/453

**Comment by Anoxia** [comment]
有一说一，文档确实很烂，很多生产环境是 centos7，gcc 的版本 4.8，gRPC 根本编译不过（gRPC submodule 拉取也是个天坑），提了几个 PR 大佬也看不上。准备逐渐弃坑，自己造一个轮子。

**Comment by heyanlong** [comment]
I am surprised to receive such comments, after all, this is beyond the scope of the current issue.

But I must remind you.
1. The Full Updates EOL of CentOS 7 is June 08, 2020. For details, please refer to https://wiki.centos.org/About/Product
1. The life cycle of GCC4.8 is from March 22, 2013 to June 23, 2015. For details, please refer to https://gcc.gnu.org/develop.html#timeline
1. The failure of gRPC clone is entirely caused by your network
1. You submitted and closed one PR which only have one line code, cannot see many PRs.
